### ISSUE TITLE
Missing compatibility with poetry 1.6.0

### ISSUE THREAD

**Issue by DBS-ST-VIT** [arcesium/poetry-plugin-pypi-mirror#10]
Hi,
our renovate bot updated our poetry version to 1.6.0 this night. While installing poetry-plugin-pypi-mirror 0.3.2, we got the following dependency error:

```text
ERROR: Cannot install poetry-plugin-pypi-mirror==0.3.2 and poetry==1.6.0 because these package versions have conflicting dependencies.
The conflict is caused by:
    The user requested poetry==1.6.0
    poetry-plugin-pypi-mirror 0.3.2 depends on poetry<1.6 and >=1.3
```

So is there a way to make this plugin compatible with the new 1.6.0 release of poetry? :)
We do not have access to the official pypi.org mirror in our company, which is why we need and love this plugin!

**Comment by JacobHenner** [comment]
Resolved by #11, thanks @waketzheng.
