### ISSUE TITLE
Read config from pyproject.toml

### ISSUE THREAD

**Issue by georgexsh** [arcesium/poetry-plugin-pypi-mirror#18]
try to configure the mirror url in pyproject.toml doesn't work:
```
[tool.poetry.plugins.pypi_mirror]
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
```
using:
poetry 1.8.3
poetry-plugin-pypi-mirror 0.4.2

I guess poetry doesn't support access `tool.poetry.plugins.*` [via `poetry.config` interface](https://github.com/arcesium/poetry-plugin-pypi-mirror/blob/master/src/poetry_plugin_pypi_mirror/plugins.py#L30-L32)?

**Comment by georgexsh** [comment]
It is possible to retrieve `pypi_mirror.url` from `poetry._pyproject.poetry_config` object, but obviously this is not a public API:
```
(Pdb) pp poetry.pyproject.poetry_config['plugins']['pypi_mirror']
{'url': 'https://example.net/simple'}
```

**Comment by JacobHenner** [comment]
Hi @georgexsh,

Could you explain your use-case a bit more? Typically this plugin is used when all requests for PyPI.org are intended to be directed to a mirror/pull-through cache, without introducing changes to `pyproject.toml` that would make it difficult to collaborate with others who would not be using the same mirror.

If you're going to be editing `pyproject.toml`, why not [declare a new primary source](https://python-poetry.org/docs/repositories/#project-configuration) without adding PyPI?

**Comment by georgexsh** [comment]
> why not [declare a new primary source](https://python-poetry.org/docs/repositories/#project-configuration) without adding PyPI?

changing the primary source would indroduce too much noise to the lock file.

> without introducing changes to pyproject.toml that would make it difficult to collaborate with others

this makes sense, I've switched to using environ to config the mirror, thanks!
